### PR TITLE
Git intro tut

### LINKED ISSUE #7: Git Intro Should Have Helpful Links
Anytime a new user "should" have something, we should include a link or something helpful for when they don't have that particular _thing_.

- [x] Installation of an IDE (VSCode?)
- [x] Installation of a compiler or interpreter (NodeJS?)
- [x] Introduction to command line
- [x] Installation of GitBash for Windows users
- [x] Link to Windows Terminal from the Microsoft Store
- [x] Instructions for setting powershell to default VSCode terminal

### PR DESCRIPTION
**Pull request by zach1590**
Completed the git-into tutorial

Packed with pictures and examples for people to follow

Tried running through it myself

### CODE REVIEW

**Review by jeffstjean — COMMENTED** [review]
I'll try running through the tutorial on Friday but I was just curious what the FizzBuzz and TwoSum scripts in different languages were for?

Love the pictures to help guide people in the right direction. Let me know if you want me to just merge it and look back at it later.

**Comment by zach1590** [comment]
You can merge it after you run it through, probably better, so If any changes are needed, I can make them before merging.

No real reason for the different languages, just there if people might know a certain language and wants to more easily read what the code is doing even though its not important. Or if someone wants to spend like 20 extra mins to get introduced to a new language they can.

Also for the first part if 2 people are doing onboarding at the same time and picked the same file to change at the same time, they would have a conflict before its explained, this would help reduce conflicts for part 1

**Comment by jeffstjean** [comment]
Can we make the README a little more in-depth? I'm imagining the transition point will be us saying "okay you're ready to code, go check out the Git Tutorial" and them hitting this page. It would be great to have step-by-step instructions on any pre-reqs (getting your username added to the org, any prelim documentation), the tutorials themselves (with links to the subdirectories to make it easy to jump to) and any post-tutorial stuff (next steps like looking through the list of Aero repos and such)

**Comment by jeffstjean** [comment]
Rename [instructions.md](https://github.com/UWO-Aero-Design/first-commit/blob/git-intro-tut/git-intro/instructions.md) to README.md so it shows up as the first thing there? People might not know that .md files are usually where you start in a repo.

Or just one README that links to instructions and help. Either or.

**Comment by jeffstjean** [comment]
[This tutorial assumes you have no prior knowledge other than what a terminal is.](https://github.com/UWO-Aero-Design/first-commit/blob/git-intro-tut/git-intro/instructions.md): let's find a generic command line tutorial for Mac, Windows, Linux to link if people don't

**Comment by jeffstjean** [comment]
Table of contents with quick links on the tutorial page would be helpful

**Comment by zach1590** [comment]
I've gone through the issue and added everything. Also put in a better repo readme section. Also added table of contents and other links so there shouldn't be chance that someone gets up to a certain point and just finds themself stuck

**Comment by jeffstjean** [comment]
Should add a small note on the push section showing what happens when you first push a branch and need the `--set-upstream` flag

**Comment by zach1590** [comment]
Doesn't --set-upstream only matter if you want to not type origin when doing fetch, pull, push? I always explicitly type origin so I'm not really sure.

I also know that these do appear when pushing for the first time. https://support.atlassian.com/bitbucket-cloud/docs/configure-your-dvcs-username-for-commits/

**Comment by jeffstjean** [comment]
Ah you're so right I never type origin

**Comment by jeffstjean** [comment]
We should have everyone push via ssh. http is such a pain and is being phased out. 

Any other changes? Looks like it's good to go :)

**Review by jeffstjean — APPROVED** [review]

**Comment by zach1590** [comment]
Last changes are just to link what to do when getting the configure user stuff. and I'll also add a link to github's how to set up an ssh key tutorial. I can do it now really quickly

edit: apparently I already added the ssh stuff. Everything is there now

**Comment by jeffstjean** [comment]
Feel free to merge when you're ready. I think you have permissions?

**Pull request merged**
